### ISSUE TITLE
save all as csv: when done, report how many files were written, and how many skipped

### ISSUE THREAD

**Issue by olarosling** [open-numbers/ddf--gapminder--life_expectancy#2]

**Comment by finarb** [comment]
Ok sure....Just give me a basic format of what columns you will like in this report....is it only numbers or what was skipped and what not?

**Comment by olarosling** [comment]
Sorry for choosing misleading word:  "report" as in two lines in the command line:
Saved 8 ddf-xlsx files as csv
Skipped 3 ddf-xlsx files because of bad sheets

**Comment by finarb** [comment]
Resolved. Please reopen if you feel otherwise.
